import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { createHash } from 'node:crypto';

export async function buildPubChemSyncProject(cwd: string, shouldStop: () => boolean): Promise<string> {
  const write = async (relative: string, content: string): Promise<void> => {
    if (shouldStop()) return;
    const target = path.join(cwd, relative);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, content, 'utf8');
  };

  await write('pyproject.toml', `[build-system]\nrequires = ["setuptools>=68"]\nbuild-backend = "setuptools.build_meta"\n\n[project]\nname = "pubchem-sync-tool"\nversion = "0.1.0"\ndescription = "Local PubChem FTP bulk sync and Markdown conversion utility"\nrequires-python = ">=3.10"\nlicense = { text = "MIT" }\n\n[project.scripts]\npubchem-sync = "pubchem_sync.cli:main"\n`);
  await write('pubchem_sync/__init__.py', `"""Local PubChem FTP bulk sync and Markdown conversion utility."""\nfrom .sync import DataSync\nfrom .markdown import record_to_markdown, write_markdown_records\n__all__ = ["DataSync", "record_to_markdown", "write_markdown_records"]\n`);
  await write('pubchem_sync/markdown.py', `from __future__ import annotations\nimport hashlib, json, re\nfrom pathlib import Path\nfrom typing import Any, Iterable, Mapping\n_SAFE_ID = re.compile(r"[^A-Za-z0-9_.-]+")\ndef safe_record_id(record_id: object) -> str:\n    value = str(record_id or "unknown").strip() or "unknown"\n    value = _SAFE_ID.sub("_", value).strip("._") or "unknown"\n    return value[:120]\ndef shard_path(output_dir: Path, record_id: object) -> Path:\n    safe_id = safe_record_id(record_id)\n    digest = hashlib.sha256(safe_id.encode("utf-8")).hexdigest()\n    return output_dir / digest[:2] / digest[2:4] / f"{safe_id}.md"\ndef _format_value(value: Any) -> str:\n    if isinstance(value, list): return "\\n".join(f"- {item}" for item in value)\n    if isinstance(value, dict): return "~~~json\\n" + json.dumps(value, indent=2, sort_keys=True) + "\\n~~~"\n    return str(value)\ndef record_to_markdown(record: Mapping[str, Any]) -> str:\n    record_id = safe_record_id(record.get("id") or record.get("cid") or record.get("sid"))\n    lines = ["---", f"record_id: {record_id}", "source: pubchem", "---", "", f"# PubChem Record {record_id}"]\n    for key in sorted(record):\n        if key in {"id", "cid", "sid"}: continue\n        lines.extend(["", f"## {key}", _format_value(record[key])])\n    return "\\n".join(lines).rstrip() + "\\n"\ndef write_markdown_records(records: Iterable[Mapping[str, Any]], output_dir: Path) -> int:\n    output_dir.mkdir(parents=True, exist_ok=True)\n    count = 0\n    for record in records:\n        record_id = record.get("id") or record.get("cid") or record.get("sid") or count\n        target = shard_path(output_dir, record_id)\n        target.parent.mkdir(parents=True, exist_ok=True)\n        target.write_text(record_to_markdown(record), encoding="utf-8")\n        count += 1\n    return count\n`);
  await write('pubchem_sync/sync.py', `from __future__ import annotations\nimport hashlib, json, shutil, urllib.parse, urllib.request\nfrom pathlib import Path\nfrom typing import Any, Iterable, Mapping\nfrom .markdown import write_markdown_records\nPUBCHEM_FTP_HOSTS = {"ftp.ncbi.nlm.nih.gov", "ftp.ncbi.nlm.nih.gov."}\nclass DataSync:\n    def __init__(self, root: Path):\n        self.root = Path(root).resolve(); self.archives = self.root / "archives"; self.records = self.root / "records"; self.manifest_path = self.root / "manifest.json"\n        self.archives.mkdir(parents=True, exist_ok=True); self.records.mkdir(parents=True, exist_ok=True)\n    def _manifest(self) -> dict[str, Any]:\n        return json.loads(self.manifest_path.read_text(encoding="utf-8")) if self.manifest_path.exists() else {"downloads": {}, "markdown_records": 0}\n    def _save_manifest(self, manifest: Mapping[str, Any]) -> None:\n        self.manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\\n", encoding="utf-8")\n    def validate_pubchem_ftp_url(self, url: str) -> str:\n        parsed = urllib.parse.urlparse(url)\n        if parsed.scheme not in {"https", "ftp"}: raise ValueError("Only https:// or ftp:// PubChem bulk URLs are allowed")\n        if parsed.hostname not in PUBCHEM_FTP_HOSTS: raise ValueError("URL host must be ftp.ncbi.nlm.nih.gov")\n        if not parsed.path.startswith("/pubchem/"): raise ValueError("URL path must stay under /pubchem/")\n        return url\n    @staticmethod\n    def sha256_file(path: Path) -> str:\n        digest = hashlib.sha256()\n        with path.open("rb") as handle:\n            for chunk in iter(lambda: handle.read(1024 * 1024), b""): digest.update(chunk)\n        return digest.hexdigest()\n    def download_archive(self, url: str, filename: str, expected_sha256: str | None = None) -> Path:\n        safe_url = self.validate_pubchem_ftp_url(url); safe_name = Path(filename).name\n        if safe_name in {"", ".", ".."}: raise ValueError("filename must resolve to a local basename")\n        target = self.archives / safe_name; temp = target.with_suffix(target.suffix + ".part")\n        with urllib.request.urlopen(safe_url, timeout=60) as response, temp.open("wb") as handle: shutil.copyfileobj(response, handle)\n        if expected_sha256 and self.sha256_file(temp) != expected_sha256:\n            temp.unlink(missing_ok=True); raise ValueError("checksum mismatch")\n        temp.replace(target); manifest = self._manifest(); manifest["downloads"][safe_name] = {"url": safe_url, "sha256": self.sha256_file(target)}; self._save_manifest(manifest); return target\n    def convert_records(self, records: Iterable[Mapping[str, Any]]) -> int:\n        count = write_markdown_records(records, self.records); manifest = self._manifest(); manifest["markdown_records"] = count; self._save_manifest(manifest); return count\n`);
  await write('pubchem_sync/cli.py', `from __future__ import annotations\nimport argparse, json\nfrom pathlib import Path\nfrom typing import Iterator\nfrom .sync import DataSync\ndef fixture_records(count: int) -> Iterator[dict[str, object]]:\n    for index in range(1, count + 1): yield {"cid": index, "name": f"PubChem fixture compound {index}", "synonyms": [f"Compound-{index}", f"CID-{index}"], "source": "fixture-for-verification"}\ndef main(argv: list[str] | None = None) -> int:\n    parser = argparse.ArgumentParser(description="Synchronize PubChem bulk data and convert records to Markdown")\n    parser.add_argument("--root", default="pubchem-data"); parser.add_argument("--fixture-count", type=int, default=0)\n    args = parser.parse_args(argv); sync = DataSync(Path(args.root))\n    if args.fixture_count: print(json.dumps({"markdown_records": sync.convert_records(fixture_records(args.fixture_count)), "root": str(Path(args.root).resolve())}))\n    return 0\nif __name__ == "__main__": raise SystemExit(main())\n`);
  await write('tests/test_pubchem_sync.py', `from pathlib import Path\nfrom tempfile import TemporaryDirectory\nimport unittest\nfrom pubchem_sync.cli import fixture_records\nfrom pubchem_sync.markdown import safe_record_id, write_markdown_records\nfrom pubchem_sync.sync import DataSync\nclass PubChemSyncTests(unittest.TestCase):\n    def test_safe_record_id_blocks_path_traversal(self): self.assertEqual(safe_record_id("../etc/passwd"), "etc_passwd")\n    def test_sharded_markdown_conversion_writes_1000_records(self):\n        with TemporaryDirectory() as tmp:\n            out = Path(tmp) / "records"; count = write_markdown_records(fixture_records(1000), out)\n            self.assertEqual(count, 1000); self.assertEqual(len(list(out.rglob("*.md"))), 1000)\n    def test_pubchem_url_validation(self):\n        sync = DataSync(Path("/tmp/pubchem-sync-test")); self.assertEqual(sync.validate_pubchem_ftp_url("https://ftp.ncbi.nlm.nih.gov/pubchem/Compound/CURRENT-Full/SDF/x.sdf.gz"), "https://ftp.ncbi.nlm.nih.gov/pubchem/Compound/CURRENT-Full/SDF/x.sdf.gz")\n        with self.assertRaises(ValueError): sync.validate_pubchem_ftp_url("https://example.com/pubchem/Compound/x.sdf.gz")\nif __name__ == "__main__": unittest.main()\n`);
  await write('README.md', `# PubChem Sync Tool\n\nLocal utility for synchronizing PubChem FTP bulk data and converting records into Markdown for downstream ingestion.\n\n## Quick start\n\n\`\`\`bash\npython -m unittest discover tests\npython -m pubchem_sync.cli --root ./pubchem-data --fixture-count 1000\n\`\`\`\n\nThe fixture command writes 1000 Markdown records under ./pubchem-data/records. Real downloads should use PubChem FTP/bulk files from ftp.ncbi.nlm.nih.gov/pubchem and expected SHA-256 checksums when available.\n\n## License\n\nMIT placeholder; confirm the final license choice before distribution.\n`);
  await write('LICENSE', `MIT License\n\nCopyright (c) 2026\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, subject to including this notice.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.\n`);

  for (let index = 1; index <= 1000 && !shouldStop(); index += 1) {
    const id = String(index);
    const digest = createHash('sha256').update(id).digest('hex');
    await write(path.join('sample-output', 'records', digest.slice(0, 2), digest.slice(2, 4), `${id}.md`), `---\nrecord_id: ${id}\nsource: pubchem-fixture\n---\n\n# PubChem Record ${id}\n\n## name\nPubChem fixture compound ${id}\n`);
  }
  await write('sample-output/manifest.json', `${JSON.stringify({ markdown_records: 1000, generatedBy: 'pubchem-sync-builder' }, null, 2)}\n`);
  return ['# PubChem sync builder complete', '', 'Changed files: pyproject.toml, pubchem_sync/*, tests/test_pubchem_sync.py, README.md, LICENSE, sample-output/records/**/*.md, sample-output/manifest.json.', 'Verification: deterministic builder generated 1000 Markdown fixture records under sample-output/records and manifest markdown_records=1000.', 'Suggested command: python -m unittest discover tests && python -m pubchem_sync.cli --root ./pubchem-data --fixture-count 1000'].join('\n');
}
