from pathlib import Path

from chem_evidence.routing_catalog import (
    SUPPORTED_DATABASES,
    render_database_index,
    render_database_readme,
    render_markdown,
    render_mermaid,
    render_svg,
)
from scripts.generate_resolver_docs import write_docs


def test_supported_database_catalog_contains_public_namespaces_and_routes():
    by_namespace = {item.namespace: item for item in SUPPORTED_DATABASES}

    for namespace in [
        "pubchem_cid",
        "pubchem_sid",
        "cas",
        "hmdb",
        "chebi",
        "kegg",
        "lipidmaps",
        "drugbank",
        "comptox",
        "splash",
    ]:
        assert namespace in by_namespace
        assert by_namespace[namespace].route
        assert by_namespace[namespace].artifact

    mermaid = render_mermaid()
    assert "graph LR" in mermaid
    assert "PubChem Compound CID" in mermaid
    assert "Xref index" in mermaid
    assert "Ranked Chemlake matches" in mermaid


def test_resolver_routing_documentation_is_generated_from_catalog(tmp_path):
    docs_dir = tmp_path / "docs"
    graph_path, markdown_path, database_readmes, svg_path, png_path = write_docs(docs_dir)

    assert graph_path.read_text(encoding="utf-8") == render_mermaid() + "\n"
    assert markdown_path.read_text(encoding="utf-8") == render_markdown() + "\n"
    assert svg_path.read_text(encoding="utf-8").startswith("<svg")
    if png_path is not None:
        assert png_path.read_bytes().startswith(b"\x89PNG")
    assert (docs_dir / "chemlake-resolver-databases" / "README.md").read_text(encoding="utf-8") == render_database_index() + "\n"
    assert len(database_readmes) == len(SUPPORTED_DATABASES)
    assert (docs_dir / "chemlake-resolver-databases" / "pubchem_cid" / "README.md").read_text(encoding="utf-8") == render_database_readme(SUPPORTED_DATABASES[0]) + "\n"
    assert "<!-- generated by scripts/generate_resolver_docs.py; edit src/chem_evidence/routing_catalog.py -->" in markdown_path.read_text(encoding="utf-8")


def test_checked_in_resolver_routing_docs_are_in_sync():
    docs = Path(__file__).resolve().parents[1] / "docs"

    assert (docs / "chemlake-resolver-routing.mmd").read_text(encoding="utf-8") == render_mermaid() + "\n"
    assert (docs / "chemlake-resolver-routing.md").read_text(encoding="utf-8") == render_markdown() + "\n"
    assert (docs / "chemlake-resolver-routing.svg").read_text(encoding="utf-8") == render_svg() + "\n"
    png = docs / "chemlake-resolver-routing.png"
    assert png.read_bytes().startswith(b"\x89PNG")
    assert (docs / "chemlake-resolver-databases" / "README.md").read_text(encoding="utf-8") == render_database_index() + "\n"
    for item in SUPPORTED_DATABASES:
        readme = docs / "chemlake-resolver-databases" / item.namespace / "README.md"
        assert readme.read_text(encoding="utf-8") == render_database_readme(item) + "\n"
