import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { parse as parseYaml } from 'yaml';
import type { AgentAdapter, AdapterConfig } from '../types/adapter.js';
import type { AgentDefinition } from '../types/agent-definition.js';
import type { PipelineConfig } from '../types/config.js';
import { createAdapter } from '../adapters/adapter-factory.js';
import { ensureOllamaReady } from '../adapters/ollama-runtime.js';
import { generateAgentFiles, buildCreationPrompt, recommendAgentCreationModels } from '../cli/agent-create-dialog.js';
import { loadAgentFromDirectory } from './loader.js';
import {
  selectHardwareFitModel,
  type HardwareModelCandidate,
  type HardwareModelSelection,
} from './model-selection.js';

export { selectHardwareFitModel, type HardwareModelCandidate, type HardwareModelSelection } from './model-selection.js';

export interface SuggestedAutonomousAgent {
  name: string;
  description: string;
}

export interface GeneratedAgentCandidateDiagnostic {
  run: number;
  name?: string;
  status: 'valid' | 'rejected' | 'failed';
  score: number;
  reason: string;
}

export interface AgentDiscoveryDiagnostics {
  status: 'created' | 'skipped' | 'failed';
  suggestedAgent: SuggestedAutonomousAgent;
  reason: string;
  model: HardwareModelSelection;
  generatedPath?: string;
  consensus: {
    method: 'three-candidates-local-judge';
    candidates: GeneratedAgentCandidateDiagnostic[];
    selectedCandidate?: number;
  };
  warnings: string[];
}

export interface DiscoverAutonomousAgentOptions {
  userTask: string;
  agentsDir: string;
  config: PipelineConfig;
  suggestedAgent: SuggestedAutonomousAgent;
  reason: string;
  installedModels?: string[];
  totalMemoryBytes?: number;
  createAdapterFn?: (config: AdapterConfig) => AgentAdapter;
  ensureModelReadyFn?: (model: string, host?: string, options?: {
    contextLength?: number;
    numParallel?: number;
    maxLoadedModels?: number;
  }) => Promise<void>;
}

export async function discoverAutonomousAgent(
  options: DiscoverAutonomousAgentOptions,
): Promise<{ agent?: AgentDefinition; diagnostics: AgentDiscoveryDiagnostics }> {
  const existingSuggested = await readExistingAgentProvenance(options.agentsDir, options.suggestedAgent.name);
  const model = selectHardwareFitModel({
    description: `${options.userTask}\n${options.suggestedAgent.name}\n${options.suggestedAgent.description}\n${options.reason}`,
    installedModels: options.installedModels ?? [],
    preferredModels: [
      options.config.agentCreation.model,
      options.config.router.model,
    ].filter(Boolean),
    ollama: options.config.ollama,
    totalMemoryBytes: options.totalMemoryBytes,
  });

  const diagnostics: AgentDiscoveryDiagnostics = {
    status: 'failed',
    suggestedAgent: options.suggestedAgent,
    reason: options.reason,
    model,
    consensus: {
      method: 'three-candidates-local-judge',
      candidates: [],
    },
    warnings: [],
  };

  if (options.config.agentOverrides[options.suggestedAgent.name]?.enabled === false) {
    diagnostics.status = 'skipped';
    diagnostics.warnings.push(`Suggested agent "${options.suggestedAgent.name}" is disabled for this run.`);
    return { diagnostics };
  }

  if (existingSuggested.exists && !existingSuggested.generated) {
    diagnostics.status = 'skipped';
    diagnostics.warnings.push(`Suggested agent "${options.suggestedAgent.name}" already exists and was not generated by router self-discovery.`);
    return { diagnostics };
  }

  const create = options.createAdapterFn ?? createAdapter;
  const adapterConfig: AdapterConfig = {
    type: options.config.agentCreation.adapter,
    model: options.config.agentCreation.model,
    ...(options.config.agentCreation.adapter === 'ollama' || options.config.agentCreation.adapter === 'huggingface'
      ? {
          host: options.config.ollama.host,
          contextLength: options.config.ollama.contextLength,
          numParallel: options.config.ollama.numParallel,
          maxLoadedModels: options.config.ollama.maxLoadedModels,
        }
      : {}),
  };

  const generated = [];
  for (let run = 1; run <= 3; run += 1) {
    try {
      const output = await runCreationCandidate(create(adapterConfig), options, model.selected.model, run);
      const files = generateAgentFiles(output);
      const candidate = validateGeneratedCandidate(files, options.suggestedAgent, model.selected.model, run);
      generated.push(candidate);
      diagnostics.consensus.candidates.push({
        run,
        name: candidate.name,
        status: 'valid',
        score: candidate.score,
        reason: candidate.reason,
      });
    } catch (err: unknown) {
      diagnostics.consensus.candidates.push({
        run,
        status: 'failed',
        score: 0,
        reason: err instanceof Error ? err.message : String(err),
      });
    }
  }

  const selected = generated.sort((a, b) => b.score - a.score || a.run - b.run)[0];
  if (!selected) {
    diagnostics.warnings.push('No valid generated agent candidate passed validation.');
    return { diagnostics };
  }

  try {
    await (options.ensureModelReadyFn ?? ensureOllamaReady)(model.selected.model, options.config.ollama.host, {
      contextLength: options.config.ollama.contextLength,
      numParallel: options.config.ollama.numParallel,
      maxLoadedModels: options.config.ollama.maxLoadedModels,
    });
  } catch (err: unknown) {
    diagnostics.warnings.push(`Selected model "${model.selected.model}" could not be verified or pulled: ${err instanceof Error ? err.message : String(err)}`);
    return { diagnostics };
  }

  diagnostics.status = 'created';
  diagnostics.consensus.selectedCandidate = selected.run;
  try {
    const directory = await writeSelectedAgent({
      agentsDir: options.agentsDir,
      files: selected,
      selectedModel: model.selected.model,
      options,
      diagnostics,
    });
    diagnostics.generatedPath = directory;
    const agent = await loadAgentFromDirectory(directory);
    return { agent, diagnostics };
  } catch (err: unknown) {
    diagnostics.status = 'failed';
    diagnostics.warnings.push(err instanceof Error ? err.message : String(err));
    return { diagnostics };
  }
}

async function runCreationCandidate(
  adapter: AgentAdapter,
  options: DiscoverAutonomousAgentOptions,
  selectedModel: string,
  run: number,
): Promise<string> {
  const recommendations = recommendAgentCreationModels(
    options.suggestedAgent.description,
    [selectedModel],
  );
  const prompt = [
    buildCreationPrompt(options.suggestedAgent.description, {
      name: options.suggestedAgent.name,
      adapter: 'ollama',
      model: selectedModel,
      outputType: 'answer',
    }, recommendations),
    '',
    `Candidate run: ${run}/3.`,
    `Original user task: ${options.userTask}`,
    `Router recovery reason: ${options.reason}`,
    'Generate a focused specialist. Do not create a broad generalist when the suggested agent description is specific.',
  ].join('\n');
  let output = '';
  for await (const chunk of adapter.run(prompt)) {
    output += chunk;
  }
  return output;
}

function validateGeneratedCandidate(
  files: { name: string; agentYaml: string; promptMd: string },
  suggested: SuggestedAutonomousAgent,
  selectedModel: string,
  run: number,
): {
  run: number;
  name: string;
  agentYaml: string;
  promptMd: string;
  score: number;
  reason: string;
} {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(files.name)) {
    throw new Error(`Generated agent name "${files.name}" is not safe kebab-case.`);
  }
  const parsed = parseYaml(files.agentYaml) as Record<string, unknown>;
  const output = parsed['output'] as Record<string, unknown> | undefined;
  if (!output || !['answer', 'data', 'files', 'presentation'].includes(String(output['type']))) {
    throw new Error(`Generated agent "${files.name}" has invalid output type.`);
  }
  if (!files.promptMd.includes('Do not use emoji') || !files.promptMd.includes('professional engineering tone')) {
    throw new Error(`Generated agent "${files.name}" did not include required conduct guardrails.`);
  }
  const suggestedTokens = tokenize(`${suggested.name} ${suggested.description}`);
  const candidateTokens = tokenize(`${files.name} ${parsed['description'] ?? ''} ${parsed['handles'] ?? ''}`);
  const overlap = suggestedTokens.filter((token) => candidateTokens.includes(token)).length;
  const exactNameBonus = files.name === suggested.name ? 50 : 0;
  const modelBonus = files.agentYaml.includes(selectedModel) ? 5 : 0;
  return {
    run,
    name: files.name,
    agentYaml: files.agentYaml,
    promptMd: files.promptMd,
    score: overlap * 10 + exactNameBonus + modelBonus,
    reason: `local judge score from suggested-agent overlap (${overlap}) and exact-name bonus (${exactNameBonus > 0 ? 'yes' : 'no'})`,
  };
}

async function writeSelectedAgent(options: {
  agentsDir: string;
  files: { name: string; agentYaml: string; promptMd: string };
  selectedModel: string;
  options: DiscoverAutonomousAgentOptions;
  diagnostics: AgentDiscoveryDiagnostics;
}): Promise<string> {
  const directory = path.join(options.agentsDir, options.files.name);
  const resolvedAgentsDir = path.resolve(options.agentsDir);
  const resolvedDirectory = path.resolve(directory);
  if (resolvedDirectory !== resolvedAgentsDir && !resolvedDirectory.startsWith(`${resolvedAgentsDir}${path.sep}`)) {
    throw new Error(`Generated agent path escapes agents directory: ${options.files.name}`);
  }
  const existing = await readExistingAgentProvenance(options.agentsDir, options.files.name);
  if (existing.exists && !existing.generated) {
    throw new Error(`Generated agent "${options.files.name}" would overwrite an existing non-generated agent.`);
  }
  if (!existing.exists && await pathExists(directory)) {
    throw new Error(`Generated agent "${options.files.name}" has an unexpected existing directory.`);
  }
  await fs.mkdir(directory, { recursive: true });
  const yaml = addGeneratedAgentMetadata(
    options.files.agentYaml,
    options.selectedModel,
    options.options,
    options.diagnostics,
  );
  await fs.writeFile(path.join(directory, 'agent.yaml'), `${yaml}\n`, 'utf8');
  await fs.writeFile(path.join(directory, 'prompt.md'), `${options.files.promptMd.trim()}\n`, 'utf8');
  return directory;
}

function addGeneratedAgentMetadata(
  agentYaml: string,
  selectedModel: string,
  options: DiscoverAutonomousAgentOptions,
  diagnostics: AgentDiscoveryDiagnostics,
): string {
  const lines = agentYaml
    .replace(/^model:\s*.*$/m, `model: ${selectedModel}`)
    .trim()
    .split('\n');
  return [
    ...lines,
    'generated: true',
    'generatedBy: router-self-discovery',
    `sourcePrompt: ${JSON.stringify(clip(options.userTask, 240))}`,
    `suggestedAgent: ${JSON.stringify(options.suggestedAgent.name)}`,
    `selectedModel: ${JSON.stringify(selectedModel)}`,
    `modelFit: ${JSON.stringify(diagnostics.model.selected.reason)}`,
  ].join('\n');
}

function tokenize(text: string): string[] {
  return text.toLowerCase().split(/[^a-z0-9]+/).filter((token) => token.length > 2);
}

function clip(text: string, maxLength: number): string {
  const compact = text.replace(/\s+/g, ' ').trim();
  return compact.length > maxLength ? `${compact.slice(0, maxLength - 3)}...` : compact;
}

async function readExistingAgentProvenance(
  agentsDir: string,
  agentName: string,
): Promise<{ exists: boolean; generated: boolean }> {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(agentName)) {
    return { exists: false, generated: false };
  }
  const yamlPath = path.join(agentsDir, agentName, 'agent.yaml');
  try {
    const raw = parseYaml(await fs.readFile(yamlPath, 'utf8')) as Record<string, unknown>;
    return {
      exists: true,
      generated: raw['generated'] === true && raw['generatedBy'] === 'router-self-discovery',
    };
  } catch {
    return { exists: false, generated: false };
  }
}

async function pathExists(target: string): Promise<boolean> {
  try {
    await fs.access(target);
    return true;
  } catch {
    return false;
  }
}
