import { loadConfig } from '../config/loader.js';
import { createAdapter } from '../adapters/adapter-factory.js';
import { assignmentToAdapterConfig } from '../tui/runtime.js';
import {
  fetchGitHubPRContext,
  parseGitHubPRUrl,
  buildPRReviewPrompt,
  postGitHubPRReview,
} from '../github/pull-requests.js';
import { resolveGitHubToken } from '../github/token.js';
import { buildPRReviewSystemPrompt } from '../prompts/pr-review-system.js';
import type { AdapterConfig, AgentAdapter } from '../types/adapter.js';
import type { GitHubPRContext, PRReviewResult } from '../types/github.js';

export interface PRReviewOptions {
  prUrl: string;
  configPath?: string;
  personality?: string;
}

export interface PRReviewHeadlessResult {
  success: boolean;
  prUrl: string;
  review: string;
  duration: number;
  githubReport?: PRReviewResult;
  error?: string;
}

type FetchLike = typeof fetch;
type AdapterFactory = (config: AdapterConfig) => AgentAdapter;

interface PRReviewDependencies {
  loadConfigFn: typeof loadConfig;
  createAdapterFn: AdapterFactory;
  fetchFn?: FetchLike;
  env?: NodeJS.ProcessEnv;
}

const defaultDependencies: PRReviewDependencies = {
  loadConfigFn: loadConfig,
  createAdapterFn: createAdapter,
};

export async function runPRReview(
  options: PRReviewOptions,
  dependencies: PRReviewDependencies = defaultDependencies,
): Promise<PRReviewHeadlessResult> {
  const startTime = Date.now();

  try {
    const config = await dependencies.loadConfigFn(options.configPath);

    const token = await resolveGitHubToken(config, dependencies.env);
    if (!token) {
      throw new Error(
        'GitHub token not found. Set GITHUB_TOKEN, add github.token to pipeline.yaml, or run "gh auth login"',
      );
    }

    const ref = parseGitHubPRUrl(options.prUrl);
    const prContext = await fetchGitHubPRContext(ref, token, dependencies.fetchFn);
    const adapterConfig = assignmentToAdapterConfig(
      config.agents.review,
      config.ollama.host,
    );
    const adapter = dependencies.createAdapterFn(adapterConfig);

    const systemPrompt = buildPRReviewSystemPrompt();
    const userPrompt = buildPRReviewPrompt(prContext);
    const fullPrompt = `${systemPrompt}\n\n---\n\n${userPrompt}`;

    const personalizedPrompt = options.personality
      ? `[PERSONALITY DIRECTIVE]\n${options.personality}\n[END PERSONALITY DIRECTIVE]\n\n${fullPrompt}`
      : fullPrompt;

    const review = await collectOutput(adapter, personalizedPrompt);

    const githubReport = await postGitHubPRReview(
      ref,
      token,
      formatReviewComment(review, prContext),
      dependencies.fetchFn,
    );

    return {
      success: true,
      prUrl: ref.url,
      review,
      duration: Date.now() - startTime,
      githubReport,
    };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      prUrl: options.prUrl,
      review: '',
      duration: Date.now() - startTime,
      error: message,
    };
  }
}

function formatReviewComment(review: string, context: GitHubPRContext): string {
  return `## MAP Code Review

**PR:** ${context.title}
**Branch:** ${context.headBranch} → ${context.baseBranch}
**Files reviewed:** ${context.files.length}

---

${review}

---
*Generated by MAP*`;
}

async function collectOutput(
  adapter: AgentAdapter,
  prompt: string,
): Promise<string> {
  let output = '';
  const controller = new AbortController();

  try {
    for await (const chunk of adapter.run(prompt, {
      allowTools: false,
      signal: controller.signal,
    })) {
      output += chunk;
    }
  } finally {
    controller.abort();
    adapter.cancel();
  }

  return output.trim();
}
